export enum ACTIVE_TYPE {
    SET_TYPE = 'SET_TYPE',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_JOKE_CATEGORY = 'SET_JOKE_CATEGORY',
    SET_VALUE = 'SET_VALUE',
    ADD_JOKE = 'ADD_JOKE',
    ADD_JOKES = 'ADD_JOKES',
    LIKED = 'LIKED',
    UNLIKED = 'UNLIKED',
}
